steps:
  # 1. Docker 이미지 빌드
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'build'
      - '-t'
      - 'asia-northeast3-docker.pkg.dev/knu-2026-sungjin0418/ai-arena/server:$COMMIT_SHA'
      - '-t'
      - 'asia-northeast3-docker.pkg.dev/knu-2026-sungjin0418/ai-arena/server:latest'
      - 'backend'

  # 2. Artifact Registry에 이미지 푸시
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'push'
      - 'asia-northeast3-docker.pkg.dev/knu-2026-sungjin0418/ai-arena/server:$COMMIT_SHA'

  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'push'
      - 'asia-northeast3-docker.pkg.dev/knu-2026-sungjin0418/ai-arena/server:latest'

  # 3. Cloud Run 재배포
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: 'gcloud'
    args:
      - 'run'
      - 'deploy'
      - 'ai-arena-server'
      - '--image'
      - 'asia-northeast3-docker.pkg.dev/knu-2026-sungjin0418/ai-arena/server:$COMMIT_SHA'
      - '--region'
      - 'asia-northeast3'
      - '--quiet'

options:
  logging: CLOUD_LOGGING_ONLY
