apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: arena
resources:
  - namespace.yaml
  - configmap.yaml
  - service-account.yaml
  - game-server-deployment.yaml
  - game-server-service.yaml
  - game-server-pdb.yaml
  - bot-runner-deployment.yaml
  - bot-runner-service.yaml
  - backend-config.yaml
  - network-policy.yaml
  - ingress.yaml
  - managed-certificate.yaml
  - hpa.yaml
